services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    command: --default-authentication-plugin=mysql_native_password
    
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: yhangrydb
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./docker/dump.sql:/docker-entrypoint-initdb.d/dump.sql
